
name: Run Cargo Tests in Nix Shell

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        run: |
          curl -L https://nixos.org/nix/install | sh
          . /home/runner/.nix-profile/etc/profile.d/nix.sh
          nix-env -iA nixpkgs.nixFlakes

      - name: Enter Nix development shell and run tests
        run: |
          . /home/runner/.nix-profile/etc/profile.d/nix.sh
          nix develop -c cargo test
