name: Run Cargo Tests in Nix Shell

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Enable Flakes
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Run tests in Nix shell
        run: |
          # Enter nix develop shell and run cargo test
          # The set -e ensures the script fails if any command fails
          set -e
          nix develop -c cargo test
